#### preprocessing-1

In [1]:
import re
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
train_data = pd.read_csv('C:/Users/moon/Desktop/5.자연어처리(실습파일)/dataset/4-1.labeledTrainData.tsv', header = 0, delimiter='\t', quoting=3)

In [30]:
def preprocessing(review, stops, remove_stopwords = True):
    review_text = BeautifulSoup(review, 'html5lib').get_text()
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    words = review_text.lower().split()
    words = [w for w in words if not w in stops]
    stemmer = PorterStemmer()
    words = [stemmer.stem(w) for w in words]
    clean_review = ' '.join(words)
    return clean_review

In [32]:
stops = set(stopwords.words('english'))
clean_train_reviews = []
for review in train_data['review']:
    r = preprocessing(review, stops, remove_stopwords = True)
    clean_train_reviews.append(r)

In [33]:
clean_train_reviews[0]

'stuff go moment mj start listen music watch odd documentari watch wiz watch moonwalk mayb want get certain insight guy thought realli cool eighti mayb make mind whether guilti innoc moonwalk part biographi part featur film rememb go see cinema origin releas subtl messag mj feel toward press also obviou messag drug bad kay visual impress cours michael jackson unless remot like mj anyway go hate find bore may call mj egotist consent make movi mj fan would say made fan true realli nice actual featur film bit final start minut exclud smooth crimin sequenc joe pesci convinc psychopath power drug lord want mj dead bad beyond mj overheard plan nah joe pesci charact rant want peopl know suppli drug etc dunno mayb hate mj music lot cool thing like mj turn car robot whole speed demon sequenc also director must patienc saint came film kiddi bad sequenc usual director hate work one kid let alon whole bunch perform complex danc scene bottom line movi peopl like mj one level anoth think peopl stay 

In [34]:
clean_train_df = pd.DataFrame({'review': clean_train_reviews,'sentiment':train_data['sentiment']})

In [36]:
clean_train_df.to_csv('C:/Users/moon/Desktop/5.자연어처리(실습파일)/saved_data/1.train_clean.csv', index = False)

preprocessing-2

In [37]:
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import pickle

In [38]:
train_data = pd.read_csv('C:/Users/moon/Desktop/5.자연어처리(실습파일)/saved_data/1.train_clean.csv')

In [39]:
reviews = list(train_data['review'])
sentiments = np.array(list(train_data['sentiment']))

In [41]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(reviews)
word2idx = tokenizer.word_index
idx2word = {v:k for k, v in word2idx.items()}
text_sequences = tokenizer.texts_to_sequences(reviews)

In [51]:
words_label = []
for review, label in zip(text_sequences, sentiments):
    for w in review:
        words_label.append([w,label])

In [82]:
word_label = np.array(word_label)

In [84]:
x = np.array([np.where(word_label[:, 1] == i)[0] for i in [0, 1]])

py = np.array([(word_label[:, 1] == i).mean() for i in [0, 1]])
N = len(idx2word)

In [85]:
py

array([0.48953997, 0.51046003])

In [86]:
mi_word = []
for i in range(1, N):
    px = (word_label[:, 0] == i).mean()
    
    mi = 0
    for y in [0, 1]:
        pxy = (word_label[x[y], 0] == i).mean()
        mi += (pxy * py[y]) * np.log(1e-8 + pxy / px)
        
    mi_word.append([mi, i])
    
    if i % 100 == 0:
        print(i, '/', N)

100 / 50597
200 / 50597
300 / 50597
400 / 50597
500 / 50597
600 / 50597
700 / 50597
800 / 50597
900 / 50597
1000 / 50597
1100 / 50597
1200 / 50597
1300 / 50597
1400 / 50597
1500 / 50597
1600 / 50597
1700 / 50597
1800 / 50597
1900 / 50597
2000 / 50597
2100 / 50597
2200 / 50597
2300 / 50597
2400 / 50597
2500 / 50597
2600 / 50597
2700 / 50597
2800 / 50597
2900 / 50597
3000 / 50597
3100 / 50597
3200 / 50597
3300 / 50597
3400 / 50597
3500 / 50597
3600 / 50597
3700 / 50597
3800 / 50597
3900 / 50597
4000 / 50597
4100 / 50597
4200 / 50597
4300 / 50597
4400 / 50597
4500 / 50597
4600 / 50597
4700 / 50597
4800 / 50597
4900 / 50597
5000 / 50597
5100 / 50597
5200 / 50597
5300 / 50597
5400 / 50597
5500 / 50597
5600 / 50597
5700 / 50597
5800 / 50597
5900 / 50597
6000 / 50597
6100 / 50597
6200 / 50597
6300 / 50597
6400 / 50597
6500 / 50597
6600 / 50597
6700 / 50597
6800 / 50597
6900 / 50597
7000 / 50597
7100 / 50597
7200 / 50597
7300 / 50597
7400 / 50597
7500 / 50597
7600 / 50597
7700 / 50597
7800 / 5

In [87]:
# mi_word 리스트를 내림차순으로 정렬한다.
mi_word.sort(reverse = True)

# MI 상위 20개 단어를 확인해 본다. Pelaez의 문서 내용과 일치하는지 확인한다.
print([idx2word[y] for x, y in mi_word[:20]])

# MI 상위 50% 단어로 vocabulrary를 생성한다.
n = int(len(mi_word) * 0.5)
word2idx2 = {idx2word[y]:(i+1) for i, [x, y] in enumerate(mi_word[:n])}
idx2word2 = {v:k for k, v in word2idx.items()}

# MI 기반 vocabulary를 이용하여 리뷰 데이터를 다시 만든다. OOV는 제거한다.
new_review = []
for review in reviews:
    r = []
    for w in review.split():
        if w in word2idx2:    # OOV 제거
            r.append(w)
    new_review.append(r)

['bad', 'worst', 'wast', 'great', 'aw', 'love', 'movi', 'stupid', 'bore', 'terribl', 'excel', 'horribl', 'wors', 'beauti', 'noth', 'best', 'poor', 'even', 'minut', 'crap']


In [91]:
mi_word = np.array(mi_word)

In [93]:
list(mi_word)

[array([6.21294353e-04, 2.30000000e+01]),
 array([3.68016342e-04, 1.71000000e+02]),
 array([3.01679511e-04, 2.22000000e+02]),
 array([2.46625852e-04, 2.50000000e+01]),
 array([2.29566975e-04, 2.94000000e+02]),
 array([1.8526761e-04, 2.8000000e+01]),
 array([1.80550295e-04, 1.00000000e+00]),
 array([1.70471836e-04, 2.86000000e+02]),
 array([1.67681578e-04, 1.83000000e+02]),
 array([1.60610006e-04, 2.77000000e+02]),
 array([1.5023816e-04, 2.1900000e+02]),
 array([1.44957578e-04, 3.91000000e+02]),
 array([1.40283782e-04, 3.83000000e+02]),
 array([1.27588027e-04, 1.24000000e+02]),
 array([1.25874033e-04, 8.10000000e+01]),
 array([1.16440302e-04, 5.20000000e+01]),
 array([1.14014893e-04, 2.84000000e+02]),
 array([1.12656383e-04, 1.30000000e+01]),
 array([1.10788492e-04, 9.90000000e+01]),
 array([1.04920645e-04, 5.14000000e+02]),
 array([9.73318894e-05, 2.74000000e+02]),
 array([9.67150349e-05, 3.08000000e+02]),
 array([9.28501186e-05, 7.75000000e+02]),
 array([8.77634647e-05, 4.00000000e+01

In [90]:
import os
if not os.path.exists('C:/Users/moon/Desktop/5.자연어처리(실습파일)/saved_data/'):
    os.makedirs(data_in_path)
    
mi_word.to_csv('C:/Users/moon/Desktop/5.자연어처리(실습파일)/saved_data/mi_word', index = False)

AttributeError: 'list' object has no attribute 'to_csv'