### 디렉토리 만들고 여러 형태로 저장하기

In [17]:
import os
if not os.path.exists(data_out_path):
    os.makedirs(data_in_path)
    
# 전처리된 데이터를 numpy 형태로 저장
np.save(open(data_in_path + train_input_data, 'wb'), train_inputs)
np.save(open(data_in_path + train_label_data, 'wb'), train_labels)

# 정제된 텍스트를 csv 형태로 저장
clean_train_df.to_csv(data_in_path + train_clean_data, index = False)

# 데이터 사전을 JSON형태로 저장
json.dump(data_configs, open(data_in_path + data_configs, 'w'), ensure_ascii=False)

NameError: name 'data_out_path' is not defined

### Dictionary, values 기준으로 정렬하기
#### sort 함수
- key 매개 변수: 단일 인자를 취하고 정렬 목적으로 사용할 키를 반환하는 함수여야 합니다.

In [14]:
name = ['a','b','c','d','e']
scores = [4,2,5,1,3]
d = dict(zip(keys,values))
print(d)

{'a': 4, 'b': 2, 'c': 5, 'd': 1, 'e': 3}


In [15]:
d_sorted = sorted(d.items(), key = lambda x: x[1], reverse=True)

In [13]:
d_sorted

[('c', 5), ('a', 4), ('e', 3), ('b', 2), ('d', 1)]

# Pandas
### display 옵션
#### df의 행, 열을 모두 출력하고 싶을 때

In [1]:
# Method 1:

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Method 2:

pd.options.display.max_columns = None
pd.options.display.max_rows = None

NameError: name 'pd' is not defined

# map vs apply vs applymap
참고 사이트  
[프로그래머 싸이님의 블로그(바로가기)](https://programmerpsy.tistory.com/22)  
[점프 투 파이썬](https://wikidocs.net/32)

## 1) map함수
> map(function, iterable)은 함수(function)와 반복가능한(iterable) 자료형을 입력으로 받는다.

- DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용해야 한다.
- 시리즈의 **모든 요소**에 함수를 일괄적용한다.
> 시리즈란?  
인덱스와 값으로 이루어진 클래스

- 시리즈는 1차원 numpy 배열과 비슷하지만, 인덱스를 붙일 수 있다.

## 2) apply함수
- DataFrame에서 사용 가능한 함수
- DataFrame의 행 또는 열에 해당하는 Series에 함수를 일괄 적용.
- axis 옵션으로 함수가 적용 될 행/열을 정할 수 있다.

In [3]:
import pandas as pd

def maxMinusMin(sr):
    return sr.max() - sr.min()

df = pd.DataFrame([[1,3,5],[4,5,6],[7,8,10]])
df.apply(maxMinusMin, axis = 0)

0    6
1    5
2    5
dtype: int64

#### return값을 조정하여 여러개 행/열로 출력 가능

In [6]:
def maxMinusMin2(sr):
    sr2 = pd.Series([sr.max(), sr.min(), sr.max()-sr.min()], index = ['최대값','최소값','차이'])
    return sr2

df.apply(maxMinusMin2, axis =0)

0  1   2
최대값  7  8  10
최소값  1  3   5
차이   6  5   5

In [7]:
df.apply(maxMinusMin2, axis =1)

최대값  최소값  차이
0    5    1   4
1    6    4   2
2   10    7   3

###  3) applymap함수
- DataFrame에서 사용가능한 함수
- DataFrame의 **모든 값**에 함수 일괄 적용

In [9]:
import numpy as np

df2 = pd.DataFrame([[1,1,1],[2,2,2],[3,3,3]])
df2.applymap(np.sqrt)

0         1         2
0  1.000000  1.000000  1.000000
1  1.414214  1.414214  1.414214
2  1.732051  1.732051  1.732051

# filter 함수
> filter(함수, 반복가능한 개체)
- 반복가능한 객체에서 **특정 조건에 맞는 요소만** 가져온다. 지정한 함수의 반환값이 True일때만 가져온다.

In [4]:
def f(x):
    return x > 5 and x < 10
a = [8,3,2,10,15,7,1,9,0,11]
list(filter(f,a))


[8, 7, 9]

# lambda 함수
[파이썬 코딩도장(바로가기)을 참고함](https://dojang.io/mod/page/view.php?id=2360)

> lambda 매개변수1, 매개변수2, ... : 매개변수를 이용한 표현식

In [7]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

list(map(lambda x: str(x) if x % 3 == 0 else x,a))

[1, 2, '3', 4, 5, '6', 7, 8, '9', 10]

# 데이터 타입 변환하기
## List <-> np.array
1) List -> Array

In [8]:
import numpy as np
lst = [1,2,3,4,5]
array = np.array(lst)
print(type(array), array, sep = '\n')

<class 'numpy.ndarray'>
[1 2 3 4 5]


2) Array -> List

In [11]:
lst1 = array.tolist()
print(type(lst1), lst1, sep = '\n')

<class 'list'>
[1, 2, 3, 4, 5]


# Stack with numpy

In [10]:
import numpy as np

a = np.arange(1,11,1)
b = np.arange(101,111,1)
c = np.arange(1001,1011,1)
print(a,b,c,sep='\n')

[ 1  2  3  4  5  6  7  8  9 10]
[101 102 103 104 105 106 107 108 109 110]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]


### vstack

In [24]:
# vstack : 행을 추가한다.(차원이 추가됨)
x = np.vstack((a,b))
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [101 102 103 104 105 106 107 108 109 110]]


In [30]:
# .T 메소드를 사용해서 추가한 행을 열로 사용할 수도 있다.
y = np.vstack((c,b)).T
print(y)

[[1001  101]
 [1002  102]
 [1003  103]
 [1004  104]
 [1005  105]
 [1006  106]
 [1007  107]
 [1008  108]
 [1009  109]
 [1010  110]]


In [59]:
print(x.T,y,x.T.shape,y.shape,sep='\n\n')

[[  1 101]
 [  2 102]
 [  3 103]
 [  4 104]
 [  5 105]
 [  6 106]
 [  7 107]
 [  8 108]
 [  9 109]
 [ 10 110]]

[[1001  101]
 [1002  102]
 [1003  103]
 [1004  104]
 [1005  105]
 [1006  106]
 [1007  107]
 [1008  108]
 [1009  109]
 [1010  110]]

(10, 2)

(10, 2)


In [60]:
# 열벡터의 경우 vstack은 hstack처럼 차원은 바뀌지 않고 그냥 이어붙인다.
print(np.vstack((x.T, y)), np.vstack((x.T, y)).shape, sep='\n')

[[   1  101]
 [   2  102]
 [   3  103]
 [   4  104]
 [   5  105]
 [   6  106]
 [   7  107]
 [   8  108]
 [   9  109]
 [  10  110]
 [1001  101]
 [1002  102]
 [1003  103]
 [1004  104]
 [1005  105]
 [1006  106]
 [1007  107]
 [1008  108]
 [1009  109]
 [1010  110]]
(20, 2)


### hstack

In [31]:
# hstck : 배열을 이어 붙인다.(차원 그대로)
np.hstack((a,b))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110])

In [44]:
print(x, y.T,sep='\n\n')

[[  1   2   3   4   5   6   7   8   9  10]
 [101 102 103 104 105 106 107 108 109 110]]

[[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]
 [ 101  102  103  104  105  106  107  108  109  110]]


In [40]:
# 다차원 배열에 hstack을 적용하면, 차원별로 이어붙인다.(차원 그대로) 
np.hstack((x,y.T))

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10, 1001,
        1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
       [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  101,
         102,  103,  104,  105,  106,  107,  108,  109,  110]])

In [62]:
np.hstack((x.T,x.T))

array([[  1, 101,   1, 101],
       [  2, 102,   2, 102],
       [  3, 103,   3, 103],
       [  4, 104,   4, 104],
       [  5, 105,   5, 105],
       [  6, 106,   6, 106],
       [  7, 107,   7, 107],
       [  8, 108,   8, 108],
       [  9, 109,   9, 109],
       [ 10, 110,  10, 110]])

### 정리
- vstack
    - 행 벡터: 차원 변경, 행 추가
    - 열 벡터: 열 벡터를 아래로 이어 붙인다.
    
- hstack
    - 행 벡터: 행 벡터 옆으로 이어 붙인다.
    - 열 벡터: 차원 변경, 열 추가